development:
  adapter: postgresql
  database: challenge_platform_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  adapter: postgresql
  database: challenge_platform_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
