development:
  adapter: postgresql
  database: challenge_platform_development
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>

test:
  adapter: postgresql
  database: challenge_platform_test
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
